version: 0.2
phases:
  install:
    commands:
      - "wget https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_arm64.zip"
      - "unzip terraform_1.2.5_linux_arm64.zip"
      - "mv terraform /usr/local/bin"
 
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo \"----Waiting to Verify to-----\"
